version: '3.7'
services:
  postgresql-server:
    image: postgres:15.0
    container_name: postgresql-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - /opt/services/postgresql-data:/var/lib/postgresql/data
    networks:
      - services_net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.0.2-ubuntu
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_STARTVMWARECOLLECTORS: 1
      ZBX_STARTCONNECTORS: 1
      ZBX_ENABLE_SNMP_TRAPS: "true"
      ZBX_STARTJAVAPOLLERS: 5
      ZBX_CACHESIZE: "128M"
    ports:
      - "10051:10051"
    volumes:
      - /opt/services/zabbix-server-data:/var/lib/zabbix
      - /opt/services/zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - /opt/services/zabbix-export-data:/var/lib/zabbix/export
      - /opt/services/zabbix-external-scripts:/usr/lib/zabbix/externalscripts
    networks:
      - services_net

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:7.0.2-ubuntu
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: dns_name
      PHP_TZ: Asia/Dubai
    ports:
      - "443:8443"
      - "8080:8080"
    volumes:
      - /opt/services/nginx-certs:/etc/ssl/nginx
      - /opt/services/conf/nginx.conf:/etc/zabbix/nginx.conf
    networks:
      - services_net
  
  zabbix-agent2:
    image: zabbix/zabbix-agent2:7.0.2-ubuntu
    container_name: zabbix-agent2
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /opt/services/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
      - /opt/services/sources.list:/etc/apt/sources.list          # If there are any custom sources.list than the default one
    privileged: true
    user: "root:root"
    networks:
      - services_net

networks:
  services_net:
    driver: bridge
